package com.foodorder.app.service;

import com.foodorder.app.config.TokenStore;
import com.foodorder.app.dto.AuthResponse;
import com.foodorder.app.dto.LoginRequest;
import com.foodorder.app.dto.RegisterRequest;
import com.foodorder.app.entity.User;
import com.foodorder.app.enums.Role;
import com.foodorder.app.exception.ApiException;
import com.foodorder.app.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

/**
 * Spring dependency injection: all collaborators (repository, password
 * encoder, token store) are injected via the constructor generated by
 * Lombok's @RequiredArgsConstructor - no manual `new` wiring anywhere.
 */
@Service
@RequiredArgsConstructor
public class UserService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final TokenStore tokenStore;

    public User register(RegisterRequest request) {
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new ApiException("Email already registered", HttpStatus.CONFLICT);
        }

        Role role;
        try {
            role = Role.valueOf(request.getRole().toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new ApiException("Role must be CUSTOMER or RESTAURANT_ADMIN", HttpStatus.BAD_REQUEST);
        }

        User user = new User();
        user.setName(request.getName());
        user.setEmail(request.getEmail());
        user.setPassword(passwordEncoder.encode(request.getPassword()));
        user.setPhone(request.getPhone());
        user.setAddress(request.getAddress());
        user.setRole(role);

        return userRepository.save(user);
    }

    public AuthResponse login(LoginRequest request) {
        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new ApiException("Invalid email or password", HttpStatus.UNAUTHORIZED));

        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new ApiException("Invalid email or password", HttpStatus.UNAUTHORIZED);
        }

        String token = tokenStore.issueToken(user.getId());
        return new AuthResponse(token, user.getId(), user.getName(), user.getRole());
    }

    public User requireUser(String token) {
        if (token == null) {
            throw new ApiException("Missing Authorization token", HttpStatus.UNAUTHORIZED);
        }
        Long userId = tokenStore.resolve(token);
        if (userId == null) {
            throw new ApiException("Invalid or expired token", HttpStatus.UNAUTHORIZED);
        }
        return userRepository.findById(userId)
                .orElseThrow(() -> new ApiException("User not found", HttpStatus.UNAUTHORIZED));
    }

    public void requireRole(User user, Role role) {
        if (user.getRole() != role) {
            throw new ApiException("Forbidden: requires role " + role, HttpStatus.FORBIDDEN);
        }
    }
}
